src/Examples/CCM/FEAppExample_1/FEAppExample_1.csproj
src/Examples/CCM/FakeCCM/FEAppTest/FEAppTest.csproj
src/Examples/CCM/FakeCCM/IdeaStatiCaFake/IdeaStatiCaFake.csproj
src/Examples/ConnHiddenCalc/ConHiddenCheckConsole/ConHiddenCheckConsole.csproj
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/IdeaStatiCa.ConnectionClient.csproj
src/Examples/IOM/IOM.SteelFrameDesktop/IOM.SteelFrameDesktop.csproj
src/IdeaStatiCa.Plugin/ApplicationBIM.cs
src/IdeaStatiCa.Plugin/AutomationHosting.cs
src/IdeaStatiCa.Plugin/BIMPluginHosting.cs
src/IdeaStatiCa.Plugin/Grpc/AutomationHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/BIMPluginHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/IPluginLogger.cs
src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/IdeaStatiCa.Plugin/NullLogger.cs
src/IdeaStatiCa.Public.sln

Updating logging mechanism, creating custom logger interface and logger.

1945 grpc wcf port

---

src/IdeaStatiCa.PluginsTools/IdeaStatiCa.PluginsTools.csproj
src/IdeaStatiCa.Public.sln

Referencing fix

---

.gitignore
src/Examples/CCM/FEAppExample_1/Properties/Resources.resx
src/Examples/CCM/FakeCCM/FEAppTest/Properties/Resources.resx
src/Examples/CCM/FakeCCM/IdeaStatiCaFake/Properties/Resources.resx
src/Examples/ConnHiddenCalc/ConnectionAutomationApp/Properties/Resources.resx
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/Properties/Resources.resx
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

Merging again with one more commit to the eval-expression.

Re-merged of eval-expression after update of texts

---

src/IdeaRS.OpenModel/Libraries/Material/MatSteelEc2.cs

Ecen steel MaterialStrength prop added

---

src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj

Solve errors in dotnet pack

---

src/IdeaStatiCa.Plugin.Tests/IdeaStatiCa.Plugin.Tests.csproj

729 public false

---

src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.cs

Update of CrossSectionFactory methods used in RFEM plugin

---

src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainVM.cs
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainWindow.xaml
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/readme.md
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/DeleteAllOperationsCommand.cs
src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

4700 apply template api

---

src/IdeaRS.OpenModel/Connection/ConnectionData.cs

4580 iom model extent by connection point id

---

src/IdeaRS.OpenModel/Connection/IdeaConImportSettings.cs

#4910 Extending of IdeaConImportSettings by the property BimAppCode

---

src/IdeaStatiCa.BimApi/IIdeaCrossSectionByName.cs
src/IdeaStatiCa.BimApi/IIdeaMaterialByName.cs
src/IdeaStatiCa.BimApi/MaterialType.cs
src/IdeaStatiCa.BimImporter.Tests/Helpers/ParameterEqualityComparer.cs
src/IdeaStatiCa.BimImporter.Tests/Importers/CrossSectionImporterTest.cs
src/IdeaStatiCa.BimImporter/Importers/AbstractImporter.cs
src/IdeaStatiCa.BimImporter/Importers/CrossSectionImporter.cs
src/IdeaStatiCa.BimImporter/Importers/MaterialImporter.cs

Added IIdeaCrossSectionByName + code cleaning

Importing of css/materials by name

---

src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.cs

T profile width haunch

---

src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs
src/IdeaStatiCa.Plugin/IIdeaStaticaApp.cs
src/IdeaStatiCa.Plugin/IdeaStatiCaAppClient.cs

6311 get connection model

---

src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs
src/Examples/CCM/FEAppExample_1/MainWindow.xaml

6335 export to modelbim

---

src/Examples/IOM/IOM.GeneratorExample/IOM.GeneratorExample.csproj
src/Examples/IOM/IOM.SteelFrameWeb/IOM.SteelFrameWeb.csproj
src/IdeaRS.OpenModel/Geometry/Geometry2D/Point.cs
src/IdeaRS.OpenModel/IdeaRS.OpenModel.csproj
src/IdeaRS.OpenModel/Parameters/Values/BoltParam.cs

Iom netstandard

---

src/IdeaStatiCa.Plugin/Constants.cs
src/IdeaStatiCa.Plugin/Utilities/IdeaStatiCaSetupTools.cs
src/IdeaStatiCa.Public.sln
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj
src/bim-links/rstab/IdeaRstabPlugin/PluginFactory.cs
src/bim-links/rstab/IdeaRstabPlugin/readme.md
src/bim-links/rstab/IdeaRstabPluginInstaller/AbstractPlugin.cs
src/bim-links/rstab/IdeaRstabPluginInstaller/DotNetPlugin.cs
src/bim-links/rstab/IdeaRstabPluginInstaller/IdeaRstabPluginInstaller.csproj
src/bim-links/rstab/IdeaRstabPluginInstaller/Program.cs
src/bim-links/rstab/IdeaRstabPluginInstaller/Properties/AssemblyInfo.cs
src/bim-links/rstab/IdeaRstabPluginInstaller/Properties/launchSettings.json
src/bim-links/rstab/IdeaRstabPluginInstaller/RSTAB.cs
src/bim-links/rstab/IdeaRstabPluginInstaller/RSTABConfig.cs
src/bim-links/rstab/IdeaRstabPluginInstaller/app.config
src/bim-links/rstab/IdeaRstabPluginInstaller/app.manifest

Get idea install folder

---

src/IdeaStatiCa.Plugin.Tests/ProjectContent/ProjectContentClientTest.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/ProjectContent/ProjectContentClientHandler.cs
src/IdeaStatiCa.Plugin/ProjectContent/ProjectContentServerHandler.cs

6715 project contenr fix

---

src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/bim-links/rstab/IdeaRstabPlugin/CheckbotCommand.cs
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj
src/bim-links/rstab/IdeaRstabPlugin/PluginFactory.cs

7399 resolver rstab

---

src/IdeaStatiCa.BimApi/IdeaStatiCa.BimApi.csproj
src/IdeaStatiCa.Public.sln

Fix BIMAPI Build

---

src/IdeaRS.OpenModel/Connection/IdeaConImportSettings.cs

6628 subcode

---

src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs

Reload FEA model in the test app while IdeaStatiCa is running

---

src/IdeaStatiCa.Public/IdeaStatiCa.Public.csproj

create nuget - ideastatica.public

---

src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainWindow.xaml

#7279 - show the button "Get Cost" on the ribbon

---

src/Examples/CCM/FEAppExample_1/Converters/InvertBooleanConverter.cs
src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs
src/Examples/CCM/FEAppExample_1/MainWindow.xaml
src/Examples/CCM/FEAppExample_1/MainWindow.xaml.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcMethodInvokerHandler.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionServiceFactory.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcServiceClient.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/IMethodInvoker.cs
src/IdeaStatiCa.Plugin/Utilities/AsyncInterceptor.cs

Fea app example grpc

---

src/IdeaStatiCa.BimImporter/IdeaStatiCa.BimImporter.csproj

nuget for IdeaStatiCa.BimImporter

---

src/IdeaStatiCa.Plugin.Tests/ProjectContent/ProjectContentServerTest.cs
src/IdeaStatiCa.Plugin.Tests/gRPC/GrpcClientTest.cs
src/IdeaStatiCa.Plugin.Tests/gRPC/GrpcReflectionServerTest.cs
src/IdeaStatiCa.Plugin.Tests/gRPC/GrpcServerTest.cs
src/IdeaStatiCa.Plugin/Grpc/AutomationHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcMethodInvokerHandler.cs
src/SystemTests/ST_GrpcCommunication/GrpcServerTest.cs

Fix duplex communication

---

src/Examples/CCM/FakeCCM/IdeaStatiCaFake/IdeaStatiCaFakeVM.cs
src/IdeaStatiCa.Plugin/Grpc/AutomationHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs

#7730 GrpcClient - fix of initialization (wrong synchronization)

---

src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

7765 hiddencalculator get set codesetup of connection

7765 hiddencalculator get set codesetup of connection

---

src/Examples/CCM/FEAppExample_1/FEAppTestVM.cs
src/Examples/CCM/FakeCCM/FEAppTest/FEAppTestVM.cs
src/IdeaStatiCa.Plugin.Tests/ProjectContent/ProjectContentClientTest.cs
src/IdeaStatiCa.Plugin/ApplicationBIM.cs
src/IdeaStatiCa.Plugin/BimHostingFactory.cs
src/IdeaStatiCa.Plugin/Grpc/AutomationHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/BIMPluginHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcMethodInvokerHandler.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionMessageHandler.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionServer.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcServiceBasedReflectionClient.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcServiceClient.cs
src/IdeaStatiCa.Plugin/ProjectContent/ProjectContentClientHandler.cs
src/bim-links/rstab/IdeaRstabPlugin/CheckbotCommand.cs

7897 frozen checkbot

---

src/IdeaStatiCa.Public/Tools/AssemblyResolver.cs

#7809 assembly resolver

---

src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Public/Tools/AssemblyResolver.cs

7804 assembly resolver etabs

---

src/IdeaStatiCa.Plugin/AutomationHosting.cs
src/IdeaStatiCa.Plugin/Grpc/AutomationHostingGrpc.cs

8207 member checkbot sync

---

src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcMethodInvokerHandler.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionMessageHandler.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionServiceFactory.cs

#7814 - Rethrow exceptions which occur in BIM Plugin in CheckBot

---

src/SystemTests/ST_GrpcCommunication/GrpcServerTest.cs

fix ProjectContentTest

---

src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionServiceFactory.cs
src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/IdeaStatiCa.RamToIdeaTest.csproj

testing of NETAnalyzers for IdeaStatiCa.Plugin

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Factories/ResultsFactory.cs

Fix condition, that recognize negative load in RAM

---

src/Examples/CCM/FakeCCM/IdeaStatiCaFake/IdeaStatiCaFake.csproj

removing TargetFrameworkSDKToolsDirectory from csproj

---

src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

9005 connection update

---

src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainVM.cs
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainWindow.xaml
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/UpdateIOMCommand.cs
src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs

example update connection

---

src/IdeaStatiCa.Plugin/Grpc/CommunicationTools.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcReflectionServiceContract.proto
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/SystemTests/ST_GrpcCommunication/GrpcServerTest.cs

Grpc message compression

---

src/IdeaRS.OpenModel/Connection/ConnectionData.cs
src/IdeaStatiCa.PluginsTools/PluginTools/Tools/Polyline.cs
src/IdeaStatiCa.PluginsTools/PluginTools/Tools/PolylineHelper.cs

iom plate new geometry definitions

9109 iom plate new geometry

---

src/IdeaStatiCa.BimApi/IdeaStatiCa.BimApi.csproj

IdeaStatiCa.BimApi to netstandard2.0

---

src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

9276 Allow setting of CSS material API

9276 Allow setting of CSS material API

---

src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

9156 modify call api

---

src/IdeaStatiCa.BimImporter/IdeaStatiCa.BimImporter.csproj

Bim importer path settings

---

src/IdeaRS.OpenModel/Setups/SteelSetupECEN.cs

#9402 Add GammaMfi to SteelSetupEcen IOM for Fire Design

#9402 Add GammaMfi to SteelSetupEcen IOM for Fire Design

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/BimApi/AbstractRamMember.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Factories/SegmentFactory.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Geometry/Geometry.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Geometry/IGeometry.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Geometry/Line.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/Geometry/LineTest.cs

* Did you find critical bug in our code? No
* Do you have any new feature you want implemented? No
* Did you fix anything? Yes

Distinct intermediate nodes on member

---

src/IdeaRS.OpenModel/Setups/ConnectionSetup.cs
src/IdeaRS.OpenModel/Setups/SteelSetupECEN.cs

#10275 add safety factor HT

---

src/bim-links/rstab/IdeaRstabPlugin/CheckbotCommand.cs

Fixed assembly resolve

---

src/IdeaStatica.BimApiLink/IdeaStatica.BimApiLink.csproj

IdeaStatica.BimApiLink - package configuration

---

src/IdeaRS.OpenModel/Parameters/Values/BoltParam.cs
src/bim-links/rstab/IdeaRstabPlugin/Factories/CrossSectionFactory.cs
src/bim-links/rstab/IdeaRstabPlugin/Factories/Utils/CssHelperFactory.cs

10786 Rstab dissallow complex user defines css

10786 Rstab dissallow complex user defines css

---

src/IdeaStatiCa.PluginsTools.Windows/IdeaStatiCa.PluginsTools.Windows.csproj
src/IdeaStatiCa.PluginsTools.Windows/Utilities/IdeaStatiCaSetupTools.cs
src/IdeaStatiCa.Public.sln
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj
src/bim-links/rstab/IdeaRstabPlugin/PluginFactory.cs

#11485 created new library for windows utilities

---

src/IdeaStatiCa.PluginsTools.Windows/IdeaStatiCa.PluginsTools.Windows.csproj
src/IdeaStatiCa.Public.sln

creating nuget package for IdeaStatiCa.PluginsTools.Windows

---

src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSection.cs
src/IdeaStatiCa.BimApi/IIdeaCrossSection.cs
src/IdeaStatiCa.BimImporter/Importers/CrossSectionImporter.cs
src/IdeaStatica.BimApiLink/BimApi/IdeaCrossSectionByComponents.cs
src/IdeaStatica.BimApiLink/BimApi/IdeaCrossSectionByName.cs
src/IdeaStatica.BimApiLink/BimApi/IdeaCrossSectionByParameters.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/BimApi/RamCrossSectionByName.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/BimApi/RamCrossSectionParametric.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Sections/AbstractRamSection.cs
src/bim-links/rstab/IdeaRstabPlugin/BimApi/RstabCrossSectionParametric.cs
src/bim-links/rstab/IdeaRstabPlugin/Model/IdeaCrossSectionByComponents.cs

11503 principal

---

src/Logger/IdeaStatiCa.PluginLogger/IdeaStatiCa.PluginLogger.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/IdeaStatiCa.RamToIdea.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/IdeaStatiCa.RamToIdeaTest.csproj
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj

nuget csproj consolidtaion (by CIH)

---

src/IdeaStatiCa.Plugin/Grpc/Reflection/Extensions.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionMessageHandler.cs
src/IdeaStatiCa.Plugin/Utilities/ReflectionHelper.cs

11294 grpcreflectionargument

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.Api/IdeaStatiCa.CheckbotPlugin.Api.csproj
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.Common.Tests/IdeaStatiCa.CheckbotPlugin.Common.Tests.csproj
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList.Tests/IdeaStatiCa.CheckbotPlugin.PluginList.Tests.csproj
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/IdeaStatiCa.CheckbotPlugin.PluginList.csproj
src/CheckbotPlugins/IdeaStatiCa.PluginRunner.Tests/IdeaStatiCa.PluginRunner.Tests.csproj
src/Examples/CCM/FEAppExample_1/FEAppExample_1.csproj
src/Examples/ConnHiddenCalc/ConHiddenCheckConsole/ConHiddenCheckConsole.csproj
src/Examples/ConnHiddenCalc/ConnectionAutomationApp/App.config
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/App.config
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/ConnectionHiddenCalculation.csproj
src/Examples/IOM/IOM.GeneratorExample/IOM.GeneratorExample.csproj
src/Examples/IOM/IOM.SteelFrameDesktop/IOM.SteelFrameDesktop.csproj
src/IdeaStatiCa.BimImporter.Tests/IdeaStatiCa.BimImporter.Tests.csproj
src/IdeaStatiCa.BimImporter/IdeaStatiCa.BimImporter.csproj
src/IdeaStatiCa.Plugin.Tests/IdeaStatiCa.Plugin.Tests.csproj
src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/SystemTests/ST_GrpcCommunication/ST_GrpcCommunication.csproj
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj
src/bim-links/rstab/IdeaRstabPluginInstaller/IdeaRstabPluginInstaller.csproj

Revert update nugets

---

src/IdeaStatiCa.BimImporter/Importers/PlateImporter.cs

11965 import allow skip material for negative plate

11965_tekla_nvol_mat

---

src/IdeaRS.OpenModel/Tools.cs
src/IdeaStatiCa.Plugin/Tools.cs

Add xml operations to the OpenModelContainer and BimModel

#11870 Add xml operations to the OpenModelContainer and BimModel

---

src/IdeaRS.OpenModel/Tools.cs

Disabled CheckCharacters
Unified xml reader/writer error
Fixed unnecessary copies

#12126 refactored xml serialization

---

src/IdeaStatiCa.BimImporter/Importers/ResultImporter.cs

#11989 fixed precision

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/IdeaStatiCa.CheckbotPlugin.PluginList.csproj
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/App.config
src/Examples/IOM/IOM.SteelFrameDesktop/App.config
src/Examples/IOM/IOM.SteelFrameWeb/App.config
src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj

Nuget update

---

src/IdeaStatiCa.Plugin/Grpc/AutomationHostingGrpc.cs
src/IdeaStatiCa.Plugin/Grpc/IGrpcCommunicationCommonInterface.cs

#12332 implemented GRPC common interface

---

src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainVM.cs
src/IdeaRS.OpenModel/Geometry/Geometry2D/ArcSegment2D.cs
src/IdeaRS.OpenModel/Geometry/Geometry2D/LineSegment2D.cs
src/IdeaRS.OpenModel/Geometry/Geometry2D/PolyLine2D.cs
src/IdeaRS.OpenModel/Geometry/Geometry2D/Region2D.cs
src/IdeaRS.OpenModel/Geometry/Geometry2D/Segment2D.cs

adding DataContract attribute to Region2D classes

---

src/IdeaStatiCa.BimApi/IIdeaModel.cs
src/IdeaStatiCa.BimImporter/BimImporter.cs
src/IdeaStatiCa.BimImporter/IBimImporter.cs
src/IdeaStatiCa.BimImporter/Importers/CutImporter.cs
src/IdeaStatiCa.Plugin/IApplicationBIM.cs
src/IdeaStatica.BimApiLink/BimApi/IdeaModel.cs
src/IdeaStatica.BimApiLink/BimLink.cs
src/IdeaStatica.BimApiLink/Plugin/CadApplication.cs
src/IdeaStatica.BimApiLink/Plugin/CadModel.cs
src/IdeaStatica.BimApiLink/Plugin/FeaModel.cs
src/IdeaStatica.BimApiLink/Plugin/ICadModel.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/BimApi/RamModel.cs
src/bim-links/rstab/IdeaRstabPlugin/BimApi/RstabModel.cs

bimlink import whole model

---

src/IdeaStatiCa.Plugin/Grpc/Services/GrpcService.cs

#13012 parameter set to optional instead of mandatory

---

src/bim-links/rstab/IdeaRstabPlugin/Factories/Utils/CssHelperFactory.cs

12122 rstab css

---

src/IdeaRS.OpenModel/Setups/ConnectionSetup.cs

new mesh setup and allGnl property

new mesh setup prop and allGnl

---

src/IdeaRS.OpenModel/Setups/ConnectionSetup.cs

12443 code setup json

---

src/IdeaRS.OpenModel/Detail/Geometry/Wall.cs
src/IdeaRS.OpenModel/Model/Element2D.cs
src/IdeaRS.OpenModel/Model/Member2D.cs
src/IdeaStatiCa.BimImporter.Tests/Importers/Element2DImporterTest.cs
src/IdeaStatiCa.BimImporter.Tests/Importers/Member2DImporterTest.cs
src/IdeaStatiCa.BimImporter.Tests/Importers/PolyLine3DImporterTest.cs
src/IdeaStatiCa.BimImporter.Tests/Importers/Region3DImporterTest.cs
src/IdeaStatiCa.BimImporter/Importers/Element2DImporter.cs

Added unit tests for Member2DImporter, Element2DImporter, Region3DImporter and PolyLine3DImporter

#12892 Added members 2D importers unit tests

---

src/IdeaRS.OpenModel/Tools.cs

13378 modelbim read file encoding

13378 modelbim readfile

---

src/IdeaStatiCa.BimApiLink/CadBimLink.cs
src/IdeaStatiCa.BimApiLink/FeaBimLink.cs
src/IdeaStatiCa.BimImporter.Tests/Persistence/JsonPersistenceTest.cs
src/IdeaStatiCa.BimImporter/Persistence/JsonPersistence.cs
src/IdeaStatiCa.BimImporter/Persistence/PersistenceTokenConverter.cs
src/bim-links/rstab/IdeaRstabPlugin/BimApiApplication.cs

* Added a diagnostics of the json parsing errors to speedup fixes of import problems.

#13296 Added logging of failure details to JsonPersistence

---

src/IdeaStatiCa.BimApiLink/Results/InternalForcesBuilder.cs
src/IdeaStatiCa.BimImporter/BimImporterConfiguration.cs
src/IdeaStatiCa.BimImporter/Importers/ResultImporter.cs

Fixed import of results

---

src/IdeaStatiCa.Plugin/IProgressMessaging.cs
src/IdeaStatiCa.Plugin/IdeaStatiCaAppClient.cs

Fixed an exception when argument is null in a method called through gRPC

---

src/IdeaStatiCa.BimApiLink/Importers/IntIdentifierImporter.cs
src/IdeaStatiCa.BimApiLink/Plugin/CadApplication.cs
src/IdeaStatiCa.BimApiLink/Plugin/ProjectAdapter.cs
src/IdeaStatiCa.BimImporter/BimImporter.cs
src/IdeaStatiCa.BimImporter/IProject.cs

* Did you find critical bug in our code? no
* Do you have any new feature you want implemented? no
* Did you fix anything? yes

Enable to synchronize model with deleted items in Bim App

---

src/IdeaRS.OpenModel/Message/OpenMessageProvider.cs
src/IdeaRS.OpenModel/Properties/Resources.Designer.cs
src/IdeaRS.OpenModel/Properties/Resources.resx

error message type operation error

#13155 operationerr msg

---

src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionParameter.cs

12586 cfrhs type

---

src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/Grpc/IGrpcServer.cs
src/IdeaStatiCa.Plugin/Grpc/IGrpcService.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionServer.cs
src/IdeaStatiCa.Plugin/Grpc/Services/GrpcService.cs

Overloading constructor GrpcServer

---

src/IdeaStatiCa.BimImporter/ImportContext.cs

* Did you find critical bug in our code? yes
* Do you have any new feature you want implemented? no
* Did you fix anything? yes

Merging multiple results data belonging to the same member

---

src/IdeaStatiCa.BimApi/IdeaStatiCa.BimApi.csproj
src/IdeaStatiCa.BimApiLink/IdeaStatiCa.BimApiLink.csproj

#12914 Set GenerateAssemblyInfo to true

---

src/Examples/CCM/FEAppExample_1/App.config
src/Examples/CCM/FEAppExample_1/Properties/Settings.Designer.cs
src/Examples/CCM/FEAppExample_1/Properties/Settings.settings
src/Examples/ConnHiddenCalc/ConHiddenCheckConsole/Properties/launchSettings.json
src/Examples/ConnHiddenCalc/ConnectionAutomationApp/App.config
src/Examples/ConnHiddenCalc/ConnectionAutomationApp/Properties/Settings.Designer.cs
src/Examples/ConnHiddenCalc/ConnectionAutomationApp/Properties/Settings.settings
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/App.config
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/Properties/Settings.Designer.cs
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/Properties/Settings.settings
src/Examples/IOM/IOM.SteelFrameDesktop/App.config
src/Examples/IOM/IOM.SteelFrameDesktop/Properties/Settings.settings

path to IDEA StatiCa v23.0

---

src/bim-links/rstab/IdeaRstabPlugin/Factories/MaterialFactory.cs

#14990 fixed import of material when cant get a material property

---

src/IdeaStatiCa.BimImporter/Persistence/JsonPersistence.cs
src/IdeaStatiCa.BimImporter/Persistence/PersistenceTokenConverter.cs

#15168 fixed exception when loading assembly during deserialization because of version mismatch

#15168 fixed exception when trying to set KeyPair in .NET6

---

src/ConnectionWebClient/ConnectionWebClient/MainWindow.xaml
src/ConnectionWebClient/ConnectionWebClient/ViewModels/MainWindowViewModel.cs
src/ConnectionWebClient/IdeaStatiCa.ConnectionClient/ConnectionClientHTTP.cs
src/ConnectionWebClient/IdeaStatiCa.ConnectionClient/IConnectionClient.cs
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainVM.cs
src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainWindow.xaml
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/CalculateBucklingCommand.cs
src/IdeaRS.OpenModel/Connection/ConnectedCheckResults.cs
src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/IConnHiddenCheck.cs

Buckling analysis api

---

src/IdeaStatiCa.BimImporter/Persistence/JsonPersistence.cs

open existing project fix.
system.core

15257 open existing project

---

src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainVM.cs
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/CloseProjectCommand.cs
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/ConnHiddenCalcCommandBase.cs
src/Examples/ConnHiddenCalc/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/OpenProjectCommand.cs
src/IdeaStatiCa.Plugin/ApplicationBIM.cs
src/IdeaStatiCa.Plugin/ConnHiddenClientFactory.cs
src/IdeaStatiCa.Plugin/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcClient.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcReflectionServer.cs
src/IdeaStatiCa.Plugin/IdeaConnectionController.cs
src/IdeaStatiCa.Plugin/WcfErrorHandler.cs

#14934 ConnectionHiddenCalculation - writing logs to file

---

src/IdeaStatiCa.Plugin/AutomationHosting.cs

#15890 Enhanced server logging

---

src/IdeaStatiCa.Public/IBlobStorageProvider.cs

Blob storage provider fix

---

src/IdeaStatiCa.BimImporter/Extensions/DoubleExtension.cs

double extension new functions

bim importer double extension

---

src/IdeaStatiCa.Plugin/IdeaConnectionController.cs

fix of the example ConnectionAutomationApp

---

src/IdeaStatiCa.BimApiLink/Utils/CrossSectionFactoryHelper.cs

15562 bim api link new parametric css

15562 bim api link new parametric css

---

src/Examples/ConnHiddenCalc/ConnectionAutomationApp/ConnectionAutomationApp.csproj
src/Examples/ConnHiddenCalc/ConnectionAutomationApp/Properties/Settings.Designer.cs

ConnectionAutomationApp as the multitarget project

---

src/Examples/ConnHiddenCalc/ConnectionHiddenCalculation/MainVM.cs
src/Logger/SerilogFacade/LoggerProvider.cs

fix - the button 'Delete Operations' doesn't work

---

src/IdeaStatiCa.BimApiLink/Utils/DoubleExtensions.cs

double extension meters in to inch

double extension meters in to inch

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/IdeaStatiCa.RamToIdeaTest.csproj

15539 fix ram csproj

---

src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.Steel.cs

Add FillRolledDoubleI for creating Double I css

---

src/IdeaStatiCa.BulkSelection/ItemsSorter.cs

#16207 bulk better node location

#16207 bulk better node location

---

examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionAutomationApp/MainVM.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionAutomationApp/MainWindow.xaml
src/IdeaStatiCa.Plugin/Api/Connection/IConnectionAutomation.cs
src/IdeaStatiCa.Plugin/Api/Connection/IConnectionController.cs
src/IdeaStatiCa.Plugin/Api/Connection/IdeaConnectionController.cs

Two additional methods for IdeaConnectionController:
- GenerateWordReport
- GeneratePdfReport

16273 Generate report endpoints

---

src/IdeaStatiCa.BimApiLink/Plugin/BimApiApplication.cs
src/bim-links/rstab/IdeaRstabPlugin/BimApiApplication.cs

* Activated logging using the IPluginLogger in IdeaStatiCa.BimApiLink and IdeaRstabPlugin.

#16766 Activated logging in BIM Link plugin and RStaab plugin

---

examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/MainVM.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/MainWindow.xaml
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/GenerateReportCommand.cs
src/IdeaStatiCa.Plugin/Api/Connection/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/Api/Connection/IConnHiddenCheck.cs

New buttons for report generating for HiddenCalculator

#16273 Add options to generate PDF & Word to hidden calculator

---

examples/bimapi/RcsApiClient/MainWindow.xaml.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientFactory.cs

RCS API is running on http instead of https, so the client needs to be adjusted.

#17233 RCS Client connecting to http

---

src/IdeaStatiCa.Plugin/Utilities/PortFinder.cs

Fix port finder

---

examples/bimapi/RcsApiClient/App.config
examples/bimapi/RcsApiClient/MainWindow.xaml
examples/bimapi/RcsApiClient/MainWindow.xaml.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/ProjectResult.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsCheckMemberModel.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsCrossSectionDetailModel.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsCrossSectionOverviewModel.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsModelOverview.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsProjectData.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsProjectInfo.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsReinforcedCrossSectionModel.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsApiController.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsController.cs
src/IdeaStatiCa.RcsClient/Client/RcsApiClient.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientFactory.cs
src/IdeaStatiCa.RcsClient/HttpWrapper/HttpClientWrapper.cs

Add support to open RCS project from OpenModel

17331 Open project from IOM

---

examples/bimapi/RcsApiClient/MainWindow.xaml.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsCrossSectionDetailModel.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsProjectInfo.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsApiController.cs
src/IdeaStatiCa.RcsClient/Client/RcsApiClient.cs

#17333 RCS API cache

---

examples/bimapi/RcsApiClient/MainWindow.xaml.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsProjectEnum.cs
src/IdeaStatiCa.Plugin/Api/RCS/Model/RcsProjectInfo.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsApiController.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsController.cs
src/IdeaStatiCa.Public.sln
src/IdeaStatiCa.RcsClient/Client/RcsApiClient.cs
src/IdeaStatiCa.RcsClient/HttpWrapper/HttpClientWrapper.cs
src/IdeaStatiCa.RcsClient/HttpWrapper/IHttpClientWrapper.cs

#17318 RCS API endpoint changes

---

examples/bimapi/RcsApiClient/ViewModels/MainWindowViewModel.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsApiController.cs
src/IdeaStatiCa.RcsClient/Client/RcsApiClient.cs
src/IdeaStatiCa.RcsClient/HttpWrapper/HttpClientWrapper.cs
src/IdeaStatiCa.RcsClient/HttpWrapper/IHttpClientWrapper.cs

Cancellation token support for RCS Api client calculation method

#17318 Cancellation token support

---

docs/.gitignore
docs/docfx.json
docs/docs/api/toc.yml
docs/docs/bimapi/toc.yml
docs/docs/iom/toc.yml

fix dev site references

---

examples/bimapi/RcsApiClient/App.xaml.cs
examples/bimapi/RcsApiClient/ViewModels/MainWindowViewModel.cs
src/IdeaStatiCa.Plugin/Api/RCS/IHeartbeatChecker.cs
src/IdeaStatiCa.Plugin/Api/RCS/IRcsClientFactory.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsApiController.cs
src/IdeaStatiCa.Plugin/Api/Rcs/IRcsController.cs
src/IdeaStatiCa.RcsClient/Client/HeartbeatChecker.cs
src/IdeaStatiCa.RcsClient/Client/RcsApiClient.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientFactory.cs

RCS Namespace unification & Default cancellation token

#17872 Namespace fix

---

.github/workflows/docfx.yml

update Docfx workflow to automate building of docs site.

Update docfx.yml to latest 

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/Providers/LoadsProvider.cs

#17894 fixed importing of loads without results

---

docs/docs/bimapi/bim_api_breaking_changes.md
docs/docs/bimapi/toc.yml

add breaking changes page for bimapi documentation

add breaking changes page for bimapi documentation

---

examples/api/csharp/connection/Connection-API-Console-Tester/ConHiddenCheckConsole/ConHiddenCheckConsole.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/ConnectionHiddenCalculation.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/IdeaStatiCa.ConnectionClient.csproj
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/RcsApiConsoleApp.csproj
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/BimLinkExampleRunner.csproj
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/BimApiLinkCadExample.csproj
examples/bimapi/CheckbotBimLink/FeaExample/BimApiLinkFeaExample/BimApiLinkFeaExample.csproj
examples/bimapi/SAF2IOM-WinForm-Tester/SAF2IOM/SAF2IOM.csproj
examples/iom/IOM/IOM.GeneratorExample/IOM.GeneratorExample.csproj
examples/iom/IOM/IOM.SteelFrameDesktop/IOM.SteelFrameDesktop.csproj
examples/iom/IOM/IOM.SteelFrameWeb/IOM.SteelFrameWeb.csproj
examples/iom/iom-rcs/IomToRcsExampleRunner/IomToRcsExampleRunner.csproj
examples/iom/iom-rcs/IomToRcsExamples/IomToRcsExamples.csproj

update of nuget IS packaget to v 23.1.3.877

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Importers/PlateImporter.cs

Tekla skip unknouwn plate - missing faces

Tekla skip unknouwn plate - missing faces

---

.github/workflows/deploy_on_tag.yml
tools/DotnetBuildTools/DotnetBuildTools.csproj
tools/DotnetBuildTools/DotnetBuildTools.sln
tools/DotnetBuildTools/NugetUpdater.cs
tools/DotnetBuildTools/Program.cs
tools/DotnetBuildTools/ProgramOptions.cs
tools/DotnetBuildTools/Properties/PublishProfiles/FolderProfile.pubxml
tools/DotnetBuildTools/Properties/launchSettings.json

Nuget updater

---

docs/docfx.json
docs/docs/api/rcs/RCSAPI-oa2.swagger.json
docs/docs/api/toc.yml

add rcs rest documentation

---

src/IdeaStatiCa.BimImporter/BimImporter.cs

Speed up of import by removing processing the whole model in order to find all nodes on a member

#18188 removed reading of the whole model to find all nodes on a member

---

examples/api/csharp/rcs/RcsApiClient/ViewModels/MainWindowViewModel.cs
examples/api/csharp/rcs/RcsApiClient/appsettings.json
python/rcsclient/ideastatica_rcs_client/rcs_client.py
src/IdeaStatiCa.Plugin/Api/RCS/IRcsClientFactory.cs
src/IdeaStatiCa.RcsClient/Client/RcsApiClient.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientFactory.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientSettings.cs

Rcs client web

---

src/IdeaStatiCa.BimImporter/BimImporter.cs
src/IdeaStatiCa.Plugin/ApplicationBIM.cs

#19064 sync bimapi fix

---

src/IdeaStatiCa.PluginsTools.Windows/IdeaStatiCa.PluginsTools.Windows.csproj

IdeaStatiCa.PluginsTools.Windows - package

---

examples/bimapi/CheckbotBimLink/readme.md

Bim api template

---

src/IdeaStatiCa.IntermediateModel/XmlParsingIRService.cs

18779 iom versioning bom fix

---

examples/api/csharp/connection/Connection-API-Console-Tester/ConHiddenCheckConsole/ConHiddenCheckConsole.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/ConnectionHiddenCalculation.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/IdeaStatiCa.ConnectionClient.csproj
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/RcsApiConsoleApp.csproj
examples/api/csharp/rcs/RcsApiClient/RcsApiClient.csproj
examples/api/csharp/rcs/RcsApiClient/ViewModels/MainWindowViewModel.cs
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/BimLinkExampleRunner.csproj
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/BimApiLinkCadExample.csproj
examples/bimapi/CheckbotBimLink/FeaExample/BimApiLinkFeaExample/BimApiLinkFeaExample.csproj
examples/bimapi/SAF2IOM-WinForm-Tester/SAF2IOM/SAF2IOM.csproj
examples/iom/IOM/IOM.GeneratorExample/IOM.GeneratorExample.csproj
examples/iom/IOM/IOM.SteelFrameDesktop/IOM.SteelFrameDesktop.csproj
examples/iom/IOM/IOM.SteelFrameWeb/IOM.SteelFrameWeb.csproj
examples/iom/iom-rcs/IomToRcsExampleRunner/IomToRcsExampleRunner.csproj
examples/iom/iom-rcs/IomToRcsExamples/IomToRcsExamples.csproj
tools/DotnetBuildTools/DotnetBuildTools.sln

Nuget update 23.1.5.0979

---

src/IdeaStatiCa.IOM.VersioningService/Extension/ModelExtension.cs

#19431 fix versioning find model

#19431 fix versioning find model

---

examples/api/csharp/connection/Connection-API-Console-Tester/ConHiddenCheckConsole/ConHiddenCheckConsole.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/ConnectionHiddenCalculation.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/IdeaStatiCa.ConnectionClient.csproj
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/RcsApiConsoleApp.csproj
examples/api/csharp/rcs/RcsApiClient/RcsApiClient.csproj
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/BimLinkExampleRunner.csproj
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/BimApiLinkCadExample.csproj
examples/bimapi/CheckbotBimLink/FeaExample/BimApiLinkFeaExample/BimApiLinkFeaExample.csproj
examples/bimapi/SAF2IOM-WinForm-Tester/SAF2IOM/SAF2IOM.csproj
examples/iom/IOM/IOM.GeneratorExample/IOM.GeneratorExample.csproj
examples/iom/IOM/IOM.SteelFrameDesktop/IOM.SteelFrameDesktop.csproj
examples/iom/IOM/IOM.SteelFrameWeb/IOM.SteelFrameWeb.csproj
examples/iom/iom-rcs/IomToRcsExampleRunner/IomToRcsExampleRunner.csproj
examples/iom/iom-rcs/IomToRcsExamples/IomToRcsExamples.csproj

nuget update to nuget version 24.0.0.3084

---

examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/BimLinkExampleRunner.csproj
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/Converters/EnumToBooleanConverter.cs
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/Properties/Settings.Designer.cs
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/Properties/Settings.settings
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/ViewModels/ApplicationType.cs
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/ViewModels/MainWindowViewModel.cs
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/Views/MainWindow.xaml

* Did you find critical bug in our code? No
* Do you have any new feature you want implemented? Yes
* Did you fix anything? No
Added CAD/FEA switch to the BimLinkExampleRunner aplication.

Add CAD/FEA switch to the BimLinkExampleRunner

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/IdentifierHelper.cs

#19913 tekla member plate fix duplicity

#19913 tekla member plate fix duplicity

---

examples/api/csharp/connection/Connection-API-Console-Tester/ConHiddenCheckConsole/Properties/launchSettings.json
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionAutomationApp/App.config
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionAutomationApp/Properties/Settings.Designer.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionAutomationApp/Properties/Settings.settings
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/App.config
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/Properties/Settings.Designer.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/Properties/Settings.settings
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/Program.cs
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/RcsCodeSamples.cs
examples/api/csharp/rcs/RcsApiClient/appsettings.json
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/BimLinkExampleRunner.csproj
examples/bimapi/CheckbotBimLink/readme.md
examples/bimapi/SAF2IOM-WinForm-Tester/SAF2IOM/SAF2IOM.csproj
examples/iom/IOM/IOM.SteelFrameDesktop/App.config
examples/iom/IOM/IOM.SteelFrameDesktop/Properties/Settings.settings
examples/iom/iom-rcs/IomToRcsExampleRunner/Program.cs
src/Examples/CCM/FEAppExample_1/App.config
src/Examples/CCM/FEAppExample_1/Properties/Settings.Designer.cs
src/Examples/CCM/FEAppExample_1/Properties/Settings.settings
src/Examples/CheckbotBimLink/BimLinkExampleConsoleApp/Program.cs

Path 24 slim

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/IdeaStatiCa.TeklaStructuresPlugin.projitems
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Importers/NodeImporter.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/TeklaCadBimLink.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/TeklaStructuresApplication.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/StringExtensions.cs

19972 tekla check old data
tekla remove node name

19972 tekla check old data

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructures2018/IdeaStatiCa.TeklaStructures2018.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2019/IdeaStatiCa.TeklaStructures2019.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2020/IdeaStatiCa.TeklaStructures2020.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2021/IdeaStatiCa.TeklaStructures2021.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2022/IdeaStatiCa.TeklaStructures2022.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2023/IdeaStatiCa.TeklaStructures2023.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2024/IdeaStatiCa.TeklaStructures2024.csproj

#19777 System management reference unification

---

src/IdeaRS.OpenModel/Detail/Geometry3D/Anchor3D.cs
src/IdeaRS.OpenModel/Detail/Geometry3D/SolidBlock3D.cs
src/IdeaRS.OpenModel/Detail/Reinforcement/ReinforcementGroup.cs

#19951 - Data iom detail

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Hooks/AppVisibilityHook.cs

#19903 tekla appvisibility hook exnded by logs

---

src/IdeaStatiCa.Public/IBlobStorageProvider.cs

#20257 IBlobStorageProvider.DeleteBlobStorage

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/TeklaStructuresApplication.cs

#20546 tekla remove check missing welds dialog

#20546 tekla remove check missing welds dialog

---

src/IdeaStatiCa.Plugin/Grpc/Services/GrpcService.cs

GrpcService.ConnectAsync - catch possible exceptions and close communication

---

docs/docs/api/api_parameter_reference_guide.md
docs/docs/api/toc.yml

update parameter expression guide

update parameter expression guide

---

examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/BimApi/Cut.cs
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/BimApi/NegativePlate.cs
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/Importers/CutImporter.cs
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/Importers/NegativePlateImporter.cs
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/Model.cs
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/TestPlugin.cs
examples/bimapi/CheckbotBimLink/CadExample/CadBulkSelection/BulkSelectionHelper.cs
examples/bimapi/CheckbotBimLink/CadExample/CadExampleApi/CadGeometryApi.cs
examples/bimapi/CheckbotBimLink/CadExample/CadExampleApi/CadObjects.cs

Add negative plate importer example and fix bulk selection for plates

Add negative plate importer example and fix bulk selection for plates

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/IdeaStatiCa.TeklaStructuresPlugin.projitems
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Importers/MemberImporter.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/MemberHelper.cs

#21051 tekla fix angle

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/BimApi/Cut.cs

#21179 tekla import fix allow nvol members

#21179 tekla import fix allow nvol members

---

src/IdeaStatiCa.PluginsTools/IdeaStatiCa.PluginsTools.csproj
src/IdeaStatiCa.PluginsTools/PluginTools/Tools/GeomOperationPoint.cs
src/IdeaStatiCa.PluginsTools/PluginTools/Tools/GeomOperationPolyLine.cs
src/IdeaStatiCa.PluginsTools/PluginTools/Tools/GeomTools2D.cs

Warning fix

---

src/IdeaRS.OpenModel/Libraries/Material/MatConcrete.cs

21338 CHN iom export fix

---

src/IdeaStatiCa.ConnectionApi/Client/ConApiClientId.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Factory/ConnectionApiClientFactory.cs
src/IdeaStatiCa.Plugin/Api/Common/IHttpClientWrapper.cs
src/IdeaStatiCa.PluginsTools/PluginTools/ApiTools/HttpWrapper.cs

Support for ClientId header in ConRestAPI

#20586 Support for HttpClientWrapper request headers

---

src/IdeaStatiCa.Plugin.Tests/gRPC/GrpcServerTest.cs
src/IdeaStatiCa.Plugin/Grpc/GrpcServer.cs
src/IdeaStatiCa.Plugin/Grpc/Services/GrpcService.cs
src/bim-links/rstab/IdeaRstabPlugin/CheckbotCommand.cs

21325 fix running member from checkbot 2

---

src/ConnectionWebClient/ConnectionWebClient.sln
src/ConnectionWebClient/ConnectionWebClient/App.xaml.cs
src/ConnectionWebClient/ConnectionWebClient/ConnectionWebClient.csproj
src/ConnectionWebClient/ConnectionWebClient/MainWindow.xaml
src/ConnectionWebClient/ConnectionWebClient/MainWindow.xaml.cs
src/ConnectionWebClient/ConnectionWebClient/ViewModels/ConnectionViewModel.cs
src/ConnectionWebClient/ConnectionWebClient/ViewModels/MainWindowViewModel.cs
src/ConnectionWebClient/ConnectionWebClient/appsettings.json
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Factory/ConnectionApiClientFactory.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiClientFactory.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.PluginsTools/PluginTools/ApiTools/HttpWrapper.cs

20347 ConnectionWebClient - use the new implementation ConnectionRestApi

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConMissingWeld.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConOperation.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Parameter/IdeaParameter.cs

#20352 Idea parameter functionality

---

src/ConnectionWebClient/ConnectionWebClient/App.xaml.cs
src/ConnectionWebClient/ConnectionWebClient/ViewModels/MainWindowViewModel.cs
src/ConnectionWebClient/ConnectionWebClient/appsettings.json
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Factory/ConnectionApiClientFactory.cs

Fix of closing of open project in ConnectionRestApi

---

src/ConnectionWebClient/ConnectionWebClient/appsettings.json

Calculators restapi UTs

---

src/IdeaStatiCa.BimApiLink/BimLink.cs
src/IdeaStatiCa.BimApiLink/CadBimLink.cs
src/IdeaStatiCa.BimApiLink/Plugin/CadModel.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/IdeaStatiCa.TeklaStructuresPlugin.projitems
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/IdeaStatiCaClient.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/IdentifierComparer.cs

#21458 bim api order items

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/Common/IHttpClientWrapper.cs
src/IdeaStatiCa.PluginsTools/PluginTools/ApiTools/HttpWrapper.cs

Heartbeat fix

---

examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/ApplySimpleTemplateCommands.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/ApplyTemplateCommand.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/CreateBoltAssemblyCommand.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/DeleteAllOperationsCommand.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/UpdateConnParamsCommand.cs
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/ConHiddenCalcCommands/UpdateLoadingCommand.cs
src/IdeaStatiCa.Plugin/Api/Connection/ConnectionHiddenCheckClient.cs
src/IdeaStatiCa.Plugin/Api/Connection/IConnHiddenCheck.cs
src/IdeaStatiCa.Plugin/Api/Connection/IdeaConnectionController.cs
src/IdeaStatiCa.Plugin/AutomationService.cs
src/IdeaStatiCa.Plugin/IAutomation.cs

* removed the UI thread blocking issues caused by calling an asynchronous methods from a synchronous code

#21328: Refactored interfaces to be asynchronous to avoid 'Not enough quota is available to process this command' errors in the Connection app

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConItem.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConLoadEffect.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConLoadEffectMemberLoad.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConLoadEffectPositionEnum.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConMember.cs

#20351 ConLoadEffect contracts

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConAnalysisTypeEnum.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConConnection.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Project/ConProject.cs

20347 con rest api get connection

---

src/IdeaStatiCa.BimApi/IIdeaElement1D.cs

Fix element 1D docs global -> local

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Settings/ConIomImportOptions.cs
src/IdeaStatiCa.PluginsTools/PluginTools/ApiTools/HttpWrapper.cs

#20346 conapi import iom

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#20351 Common diagnostics for API endpoints

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs

#20358 new con api export iom

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs

#21532 connection new api update by iom model

#21532 connection new api update by iom model

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConCalculationParameter.cs

Conrestapi more ut

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.PluginsTools/PluginTools/ApiTools/HttpWrapper.cs

Apply template

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs

IConnectionApiController.GetOperationsAsync

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConProductionCost.cs

Production cost function

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/IdeaStatiCa.CheckbotPlugin.PluginList.csproj

fixed System.Text.Json version

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConMember.cs

Updating ConMember in preparation for member endpoints

20353 member controller

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList.Tests/Integration/PluginListTest.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Descriptors/PluginDescriptor.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Descriptors/TabInfoDescriptor.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Json/Plugin.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Json/TabInfo.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Mappers/Mapper.Plugin.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Mappers/Mapper.TabInfo.cs

Create TabInfo where can be specified if new tab for Checkbot plugin is needed or if the plugin can be places in the Plugins tab

Create options to place plugin for Checkbot in separate tab if needed

---

src/IdeaRS.OpenModel/Connection/ConnectionCheckRes.cs

#20349 Add connection ID

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConAnalysisTypeEnum.cs

#20349 Add buckling analysis type

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs

#20353 connection api client member functions

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/Common/IHttpClientWrapper.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.PluginsTools/PluginTools/ApiTools/HttpWrapper.cs

21742 Delete request support

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.Protos/project_service.proto
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin/Models/ModelExportOptions.cs

#20507 checkbotplugin get versioned iom - possibility to downgrade

#20507 checkbotplugin get versioned iom

---

src/CheckbotPlugins/ExamplePlugin/Plugin.cs
src/CheckbotPlugins/ExamplePlugin/PluginMain.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.Protos/project_service.proto
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin/Models/ProjectInfo.cs
src/IdeaRS.OpenModel/Connection/ConProjectInfo.cs

checkbot plugin project info extended by sourceapp

20679 hilti proj info

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/ConRestApiConstants.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs

21704 connection api routes refactoring

---

src/IdeaStatiCa.Plugin/Api/Connection/IConnectionController.cs
src/IdeaStatiCa.Plugin/Api/Connection/IdeaConnectionController.cs
src/IdeaStatiCa.Plugin/AutomationService.cs
src/IdeaStatiCa.Plugin/IAutomation.cs

* Added new methods that allow closing the project asynchronously.

#21200: Added support of an asynchronous closing of the project

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConItem.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConLoadEffect.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Connection/ConMember.cs

Fix connection rest api ut

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/IdeaStatiCa.RamToIdeaTest.csproj

* updated NUnit to 3.14.0
* updated UNit3TestAdapter to 4.5.0

#21200: Updated NUnit to 3.14.0, updated UNit3TestAdapter to 4.5.0

---

src/Logger/IdeaStatiCa.PluginLogger/IdeaStatiCa.PluginLogger.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/IdeaStatiCa.RamToIdeaTest.csproj
src/bim-links/rstab/IdeaRstabPlugin/IdeaRstabPlugin.csproj

Serilog NuGet updated to 4.0.0

21200 update Serilog to 4.0.0

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/ConRestApiConstants.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Project/ProjBoltAssembly.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Project/ProjCrossSection.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Project/ProjItem.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Project/ProjMaterial.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Project/ProjPin.cs

#20350 Materials controller

---

src/IdeaStatiCa.Plugin/Utilities/JsonTools.cs

RestAPI Calculators - serialize enums as strings in Calculators

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Template/Mappings/BaseTemplateConversion.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/Model/Model_Template/Mappings/ConversionTypes.cs

ConversionTypes - NotSet

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs
src/IdeaStatiCa.Plugin/Api/ConnectionRest/IConnectionApiController.cs

Add parameter to C# client

---

src/IdeaStatiCa.Plugin/Api/ConnectionRest/ConRestApiConstants.cs

#22028 Version endpoint constant

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#22185 Material fix

---

src/IdeaRS.OpenModel/IdeaRS.OpenModel.csproj
src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.ColdFormed.cs
src/IdeaRS.OpenModel/Libraries/CrossSection/CrossSectionFactory.Steel.cs
src/IdeaRS.OpenModel/Tools.cs

Iom fix source comments

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

Implementation of GetVersion

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

renaming apply-mapping -> get-template-mapping

---

src/IdeaStatiCa.Api/Connection/ConRestApiConstants.cs
src/IdeaStatiCa.Plugin/Api/Connection/IConnectionAutomation.cs
src/IdeaStatiCa.Plugin/Api/Connection/IConnectionController.cs
src/IdeaStatiCa.Plugin/Api/Connection/IdeaConnectionController.cs

#20354 Report with Connection API

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#20354 Get default mapping client change

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#22185 Material controller does not contain connectionId

---

src/IdeaStatiCa.Api/Connection/Model/Template/Mappings/BaseTemplateConversion.cs

#22338 Simplify template conversion object for API

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

GetConnectionTemplateAsync

---

src/ConnectionWebClient/ConnectionWebClient/ViewModels/MainWindowViewModel.cs
src/ConnectionWebClient/ConnectionWebClient/appsettings.json
src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

Providing information abou active connections

---

src/IdeaStatiCa.Api/Utilities/JsonTools.cs

#21371 3D Scene Json Serialization

---

src/IdeaStatiCa.Api/Common/HttpWrapper.cs
src/IdeaStatiCa.Api/Common/IHttpClientWrapper.cs
src/IdeaStatiCa.Api/Connection/ConRestApiConstants.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#22508 ConnectionAPI naming

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#22575 Connection Project data

---

src/IdeaStatiCa.BimImporter.Tests/IdeaStatiCa.BimImporter.Tests.csproj
src/IdeaStatiCa.Plugin.Tests/IdeaStatiCa.Plugin.Tests.csproj
src/SystemTests/SystemTestService/SystemTestService.csproj

Net6 migration

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.Api/Connection/Model/Connection/ConConnection.cs
src/IdeaStatiCa.Api/Connection/Model/Connection/ConLoadSettings.cs
src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

#22569 LoadSettings

---

src/IdeaStatiCa.Plugin/Api/Connection/IdeaConnectionController.cs
src/IdeaStatiCa.Plugin/AutomationService.cs
src/IdeaStatiCa.Plugin/IAutomation.cs

#22572 OpenProject(string fileName, string optionalParamJson)

---

examples/bimapi/CheckbotBimLink/FeaExample/BimApiLinkFeaExample/Model.cs
src/IdeaStatiCa.BimApiLink/Plugin/FeaApplication.cs
src/IdeaStatiCa.BimApiLink/Plugin/FeaModel.cs
src/IdeaStatiCa.BimApiLink/Plugin/FeaUserSelection.cs
src/IdeaStatiCa.BimApiLink/Plugin/IFeaModel.cs
src/IdeaStatiCa.BimImporter/BimImporter.cs

- revert
- improvements of FeaModelAdapter and IFeaModel

22550 i fea model improvements

---

src/IdeaStatiCa.ConnectionApi/Client/ConnectionApiController.cs

fix content-type

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/IdeaStatiCa.CheckbotPlugin.PluginList.csproj

json update to 8.0.5

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/IdeaStatiCa.CheckbotPlugin.PluginList.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/IdentifierHelper.cs

Json update merge from main

---

src/IdeaStatiCa.Api/Common/HttpWrapper.cs
src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs

Conrestapi iom

---

.github/workflows/publish-conclient-pip.yml

workflow - uploading python client to PIP

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.Api/Connection/Model/Connection/ConConnection.cs

#23555 Small improvements

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs

#23554 Change add object type

---

examples/api/csharp/connection/Connection-API-Console-Tester/ConHiddenCheckConsole/ConHiddenCheckConsole.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/ConnectionHiddenCalculation/ConnectionHiddenCalculation.csproj
examples/api/csharp/connection/Connection-API-WinForm-Tester/IdeaStatiCa.ConnectionClient/IdeaStatiCa.ConnectionClient.csproj
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/RcsApiConsoleApp.csproj
examples/api/csharp/rcs/RcsApiClient/RcsApiClient.csproj
examples/bimapi/CheckbotBimLink/BimLinkExampleRunner/BimLinkExampleRunner.csproj
examples/bimapi/CheckbotBimLink/CadExample/BimApiLinkCadExample/BimApiLinkCadExample.csproj
examples/bimapi/CheckbotBimLink/FeaExample/BimApiLinkFeaExample/BimApiLinkFeaExample.csproj
examples/bimapi/SAF2IOM-WinForm-Tester/SAF2IOM/SAF2IOM.csproj
examples/iom/IOM/IOM.GeneratorExample/IOM.GeneratorExample.csproj
examples/iom/IOM/IOM.SteelFrameDesktop/IOM.SteelFrameDesktop.csproj
examples/iom/IOM/IOM.SteelFrameWeb/IOM.SteelFrameWeb.csproj
examples/iom/iom-rcs/IomToRcsExampleRunner/IomToRcsExampleRunner.csproj
examples/iom/iom-rcs/IomToRcsExamples/IomToRcsExamples.csproj

IS nuget 24.1.0.3003

---

examples/bimapi/CheckbotBimLink/CppFeaExample/CppFeaApiWrapper/CppFeaApiWrapper.vcxproj
examples/bimapi/CheckbotBimLink/CppFeaExample/CppFeaApiWrapper/Model.cpp
examples/bimapi/CheckbotBimLink/CppFeaExample/CppFeaApiWrapper/Model.h
examples/bimapi/CheckbotBimLink/CppFeaExample/ImporterWrappers/ImporterWrappers.csproj

Cpp example nuget update

---

examples/bimapi/CheckbotBimLink/SAF/CppSafFeaExample/readme.md

cpp saf - readme

---

src/IdeaStatiCa.IOM.VersioningService/Configuration/ConfigurationStepService.cs

fix diagnostics

---

examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/Program.cs
examples/api/csharp/rcs/Rcs-Api-Console-Tester/RcsConsoleApp/RcsCodeSamples.cs
examples/api/csharp/rcs/RcsApiClient/App.xaml.cs
examples/iom/iom-rcs/IomToRcsExampleRunner/Program.cs
src/IdeaStatiCa.Api/RCS/Model/RcsProject.cs
src/IdeaStatiCa.Api/RCS/Model/RcsProjectSummary.cs
src/IdeaStatiCa.Api/RCS/RcsRestApiConstants.cs
src/IdeaStatiCa.RcsClient/Client/RcsApiClientObsolete.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientFactory.cs
src/IdeaStatiCa.RcsClient/Factory/RcsClientFactoryObsolete.cs

#23644 Update URIs for RCS API

---

src/api-sdks/connection-api/clients/python/tests/test_ideastatica_connection_api.py

adding pytest test_should_apply_template

---

.github/workflows/dotnet.yml
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList.Tests/IdeaStatiCa.CheckbotPlugin.PluginList.Tests.csproj
src/IdeaStatiCa.Api/IdeaStatiCa.Api.csproj
src/IdeaStatiCa.BimImporter.Tests/IdeaStatiCa.BimImporter.Tests.csproj
src/IdeaStatiCa.BimImporter/Persistence/JsonPersistence.cs
src/IdeaStatiCa.IOM.VersioningServiceTests/IdeaStatiCa.IOM.VersioningServiceTests.csproj
src/IdeaStatiCa.IntermediateModel.Tests/IdeaStatiCa.IntermediateModel.Tests.csproj
src/IdeaStatiCa.Plugin.Tests/IdeaStatiCa.Plugin.Tests.csproj
src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/IdeaStatiCa.RcsClient/IdeaStatiCa.RcsClient.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaTest/IdeaStatiCa.RamToIdeaTest.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2022/IdeaStatiCa.TeklaStructures2022.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresTest/IdeaStatiCa.TeklaStructuresTest.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresTest/NodeImporterTest.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresTest/WorkPlaneImporterTest.cs

This reverts commit 2ed824be9aaaf30e49e0f076a177eb9192243a9f.

Revert "nuget update (#713)"

---

src/api-sdks/connection-api/clients/python/examples-pip/calculate-hss/calculate-hss.py
src/api-sdks/connection-api/clients/python/examples/Calculate_HSS_norm_cond/calculate-hss.py
src/api-sdks/connection-api/clients/python/examples/apply-template/apply-template.py
src/api-sdks/connection-api/clients/python/examples/generate-report/generate-report.py
src/api-sdks/connection-api/clients/python/examples/import-export/import-export.py
src/api-sdks/connection-api/clients/python/ideastatica_connection_api/api_ext/project_ext_api.py
src/api-sdks/connection-api/clients/python/ideastatica_connection_api/connection_api_client.py
src/api-sdks/connection-api/clients/python/ideastatica_connection_api/connection_api_service_attacher.py
src/api-sdks/connection-api/clients/python/ideastatica_connection_api/connection_api_service_runner.py
src/api-sdks/connection-api/clients/python/tests/test_ideastatica_connection_api.py

- Implement enter and exit method for client so closing can be done automatically at the end of "with" statement
- Client take base_url as parameter instead of Configuration (same as in C#..)
- Add open_project_from_filepath to project_api_ext to add same funcionality as we have in C#
- Small impoments in Attacher and Runner classes

Small improvemets

---

src/IdeaStatiCa.Api/Connection/Model/Template/Mappings/MemberTemplateConversion.cs

#24405 Serialize members

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/IdentifierHelper.cs

24461tekla member cut fix recognition

---

src/IdeaStatiCa.BulkSelection/ItemsSorter.cs

typology grouping bugfix

---

src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/Api/OperationApi.cs
src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/Client/Configuration.cs
src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/IdeaStatiCa.ConnectionApi.csproj
src/api-sdks/connection-api/clients/python/ideastatica_connection_api/api/operation_api.py

Update OperationApi for Csharp and Python client

---

Directory.Packages.props
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/ClientExamples.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/CodeSamples.csproj
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Program.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/AddBoltAssembly.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/AddCrossSection.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/AddLoadEffect.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/ApplyTemplate.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/ExportIFC.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/ExportIom.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/ExportIomConnectionData.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/GeneratePdf.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/GenerateWord.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/ImportIOM.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/SetBearingMember.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/UpdateLoadEffect.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/UpdateMember.cs
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Samples/UpdateParameters.cs
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ConApiWpfClientApp.csproj
src/api-sdks/connection-api/clients/csharp/src/tests/ST_ConRestApiClient/ST_ConRestApiClient.csproj
src/api-sdks/rcs-api/clients/csharp/examples/CodeSamples/CodeSamples.csproj
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/MainWindow.xaml
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/RcsApiWpfClientApp.csproj
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/appsettings.json
src/api-sdks/rcs-api/clients/csharp/src/tests/ST_RcsRestApiClient/RcsRestApiBaseTest.cs
src/api-sdks/rcs-api/clients/csharp/src/tests/ST_RcsRestApiClient/RcsRestApiIomTest.cs
src/api-sdks/rcs-api/clients/csharp/src/tests/ST_RcsRestApiClient/RcsRestApiTests.cs
src/api-sdks/rcs-api/clients/csharp/src/tests/ST_RcsRestApiClient/ST_RcsRestApiClient.csproj

Add service attacher and runner to code examples

---

src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/IdeaStatiCa.ConnectionApi.csproj

downgraded version of Polly to mach the CPM

---

Directory.Packages.props
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2020/IdeaStatiCa.TeklaStructures2020.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/IdeaStatiCaClient.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/ModelClient.cs

#24214 tekla fix net6 migration

---

src/api-sdks/connection-api/clients/python/examples/calculate_project_using_runner/README.md
src/api-sdks/connection-api/clients/python/examples/calculate_project_using_runner/calculate_project_using_service_runner.py
src/api-sdks/rcs-api/clients/python/examples-pip/calculate_project_using_runner/README.md
src/api-sdks/rcs-api/clients/python/examples-pip/calculate_project_using_runner/calculate_project_using_service_runner.py
src/api-sdks/rcs-api/clients/python/examples-pip/calculate_project_using_runner/requirements.txt

add exaples with service runner to both api

---

src/IdeaStatiCa.Plugin/ApplicationBIM.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/ApplicationBimAsync.cs

use logger from the base class

---

src/IdeaStatiCa.Plugin/ApplicationBIM.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/ApplicationBimAsync.cs

fix - protected logger

---

src/IdeaStatiCa.BimImporter/Persistence/JsonPersistence.cs

Assemblies load from

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/StartupService.cs

#24853 Unused variable removed

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/RamPluginFactory.cs

#24856 Correct path for RAM

---

src/IdeaStatiCa.BimImporter/Persistence/JsonPersistence.cs
src/IdeaStatiCa.Plugin/Grpc/BIMPluginHostingGrpc.cs

#25073 rfem 5 bug

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/IdeaStatiCa.RamToIdea.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/IdeaStatiCa.RamToIdeaApp.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/RamFeaApplication.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/RamPluginFactory.cs

Keep RamToIdea exe on net48

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/FolderHelper.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/RamPluginFactory.cs

Search checkbot in correct folder

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/FolderHelper.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/RamPluginFactory.cs

Folder location diagnostics

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/IdeaStatiCa.RamToIdeaApp.csproj

ram add runtime tag

---

Directory.Packages.props
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/IdeaStatiCa.CheckbotPlugin.PluginList.csproj
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.Protos/IdeaStatiCa.CheckbotPlugin.Protos.csproj
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin/IdeaStatiCa.CheckbotPlugin.csproj
src/IdeaStatiCa.BimImporter/IdeaStatiCa.BimImporter.csproj
src/IdeaStatiCa.NetFrameworkPort/IdeaStatiCa.NetFrameworkPort.csproj
src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/IdeaStatiCa.RamToIdea.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2018/IdeaStatiCa.TeklaStructures2018.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2019/IdeaStatiCa.TeklaStructures2019.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2020/IdeaStatiCa.TeklaStructures2020.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2021/IdeaStatiCa.TeklaStructures2021.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2022/IdeaStatiCa.TeklaStructures2022.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2023/IdeaStatiCa.TeklaStructures2023.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2024/IdeaStatiCa.TeklaStructures2024.csproj

There was some double referenced libraries and some dlls was copied from multiple different sources this should fix it

Fix references

---

src/api-sdks/connection-api/clients/csharp/README.md
src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/Program.cs
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/appsettings.json
src/api-sdks/connection-api/clients/python/README.md
src/api-sdks/connection-api/clients/python/examples/README.md
src/api-sdks/connection-api/clients/python/examples/calculate_project_using_runner/calculate_project_using_service_runner.py
src/api-sdks/rcs-api/clients/csharp/README.md
src/api-sdks/rcs-api/clients/python/README.md
src/api-sdks/rcs-api/clients/python/examples-pip/calculate_project_using_runner/calculate_project_using_service_runner.py

path for setup IS 24.1.3 (without net6.0-windows)

---

src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj

Plugin.csproj edit

---

src/IdeaStatiCa.Plugin/IdeaStatiCa.Plugin.csproj

Remove package require license

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdea/IdeaStatiCa.RamToIdea.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/IdeaStatiCa.RamToIdeaApp.csproj

Revert RAM update

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/ModelClient.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/BulkSelectionHelper.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/IdentifierHelper.cs

tekla_fix_bulk_for_anchors

---

docs/docs/api/api_parameter_reference_guide.md

GetQuadrant doc

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.Api/Connection/Model/Conversion/ConConversionSettings.cs

Conversion controller contracts

---

src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/ConnectionApiClient.cs

Api client without timeout

---

src/IdeaStatiCa.Plugin/Exeptions/BulkSelectionOverflowException.cs
src/IdeaStatiCa.Plugin/Grpc/Reflection/GrpcMethodInvokerHandler.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/BulkSelectionHelper.cs

#26229 api add bulk exception for selection overflow

---

src/IdeaStatiCa.Public/IBlobStorageProvider.cs

Refresh blob storage method

---

Directory.Packages.props
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/App.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/App.xaml.cs
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/AssemblyInfo.cs
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/ConversionBulkTool.csproj
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/CustomConversion.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/CustomConversion.xaml.cs
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml.cs
src/api-sdks/connection-api/clients/csharp/examples/IdeaStatiCa.ConnectionApi.Examples.sln

Conversion bulk tool

---

src/IdeaStatiCa.Api/Connection/Model/Conversion/ConConversionSettings.cs
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/ConversionBulkTool.csproj

Conversion settings incorrect serialization

---

src/IdeaStatiCa.BimImporter.Tests/IdeaStatiCa.BimImporter.Tests.csproj
src/IdeaStatiCa.BimImporter.Tests/Persistence/JsonPersistenceTest.cs
src/IdeaStatiCa.BimImporter.Tests/TestData/bimapi-data-serialized-with-all.json
src/IdeaStatiCa.BimImporter.Tests/TestData/bimapi-data-serialized-with-auto.json
src/IdeaStatiCa.BimImporter.Tests/TestData/bimapi-data-serialized-with-none.json

Adding basic tests for deserialization of json. 
Following cases are tested:
- deserialization of json serialized with 'TypeNameHandling.All' option
- deserialization of json serialized with 'TypeNameHandling.Auto' option
- deserialization of json serialized with 'TypeNameHandling.None' option

27082 Tests for deserialization of json

---

src/IdeaStatiCa.Api/Connection/Model/Conversion/ConConversionSettings.cs
src/IdeaStatiCa.Api/Connection/Model/Parameter/IdeaParameter.cs
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml.cs

Add bounds to IdeaParameter

---

docs/docs/api/api_parameter_reference_guide.md

Parameter functions doc

---

src/api-sdks/connection-api/clients/csharp/examples/CodeSamples/CodeSamples.csproj
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClient.sln
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ConApiWpfClientApp.csproj

Fix example ConApiWpfClient.sln

---

src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClient-deve.sln
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ConApiWpfClientApp.csproj
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ViewModels/MainWindowViewModel.cs
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/README.md

Wpf example templates

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/IdentifierHelper.cs

#27434 tekla fix add bolts welds for connection component component

---

src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml.cs

ConversionBulkTool disposing service when closed

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/App.xaml.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/IdeaStatiCa.RamToIdeaApp.csproj
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/IStartupService.cs
src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/Services/StartupService.cs

RAM Agata preparation

---

src/IdeaStatiCa.BulkSelection/ItemsSorter.cs

#27507 bulk fix item sorter comparer

---

src/IdeaStatiCa.IOM.VersioningService/Downgrade/DowngradeService.cs
src/IdeaStatiCa.NetFrameworkPort/IdeaStatiCa.NetFrameworkPort.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/ModelClient.cs

27539 clean err

---

src/IdeaStatiCa.BimApiLink/IdeaStatiCa.BimApiLink.csproj
src/IdeaStatiCa.PluginsTools/IdeaStatiCa.PluginsTools.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2018/IdeaStatiCa.TeklaStructures2018.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2019/IdeaStatiCa.TeklaStructures2019.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2020/IdeaStatiCa.TeklaStructures2020.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2021/IdeaStatiCa.TeklaStructures2021.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2022/IdeaStatiCa.TeklaStructures2022.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2023/IdeaStatiCa.TeklaStructures2023.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2024/IdeaStatiCa.TeklaStructures2024.csproj
src/bim-links/tekla/IdeaStatiCa.TeklaStructures2025/IdeaStatiCa.TeklaStructures2025.csproj

Fix dependencies for net8 #27541

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/App.xaml.cs

Don't use async file creation

---

src/bim-links/bentley-ram/IdeaStatiCa.RamToIdeaApp/App.xaml.cs

Ram agata changes

---

src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/CustomConversion.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml.cs

Rename Bulk tool

---

src/IdeaStatiCa.Api/Connection/Model/Parameter/IdeaParameter.cs
src/IdeaStatiCa.Api/Connection/Model/Parameter/ParameterUpdateResponse.cs

Parameter validation objects

---

src/IdeaStatiCa.Api/Common/IApiClient.cs
src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/ConnectionApiClient.cs
src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/IConnectionApiClient.cs
src/api-sdks/rcs-api/clients/csharp/src/IdeaStatiCa.RcsApi/IRcsApiClient.cs

Add common interface for APIs

---

src/api-sdks/rcs-api/clients/python/examples-pip/load-update-ex1/README.md

Rcs loading

---

src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ViewModels/MainWindowViewModel.cs

Example : export connection to IOM and IFC

---

src/IdeaStatiCa.Api/Connection/Model/Connection/ConMember.cs

ConMemberPlatePartTypeENum

---

src/IdeaRS.OpenModel/Result/Member2DReactExtensions.cs
src/IdeaStatiCa.BimApiLink/Persistence/Interfaces/IProjectStorage.cs
src/IdeaStatiCa.BimApiLink/Persistence/Interfaces/IProjectStorageReader.cs
src/IdeaStatiCa.BimApiLink/Persistence/Interfaces/IProjectStorageValidator.cs
src/IdeaStatiCa.BimApiLink/Persistence/Interfaces/IProjectStorageWriter.cs
src/IdeaStatiCa.BimApiLink/Persistence/JsonProjectStorageReader.cs
src/IdeaStatiCa.BimApiLink/Persistence/ProjectStorage.cs
src/IdeaStatiCa.BimApiLink/Persistence/ProjectStorageBase.cs
src/IdeaStatiCa.BimApiLink/Persistence/ProjectStorageFactory.cs

Split IProjectStorage interfaces to multiple smaller ones
Create factory for ProjectStorage

ProjectStorage modification

---

src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/App.xaml.cs
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ConApiWpfClientApp.csproj
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/MainWindow.xaml.cs
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ViewModels/MainWindowViewModel.cs
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/appsettings.json

Present scene3d example

---

src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/MainWindow.xaml
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ViewModels/MainWindowViewModel.cs

ConApiWpfClientApp : offer more analysis types

---

src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Descriptors/ActionButtonDescriptor.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Descriptors/PluginToolTipDescriptor.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Descriptors/TabInfoDescriptor.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Json/ActionButton.cs
src/CheckbotPlugins/IdeaStatiCa.CheckbotPlugin.PluginList/Mappers/Mapper.ActionButton.cs

plugin tab tooltip descriptor

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/IdeaStatiCa.Api/Connection/Model/Connection/ConConnection.cs
src/IdeaStatiCa.Api/Connection/Model/Connection/ConWeldSizingMethodEnum.cs
src/IdeaStatiCa.Api/Connection/Model/Project/ConOperationCommonProperties.cs

21374 Contracts for weld sizing

---

src/IdeaStatiCa.Plugin/Api/Connection/IdeaConnectionController.cs
src/IdeaStatiCa.Plugin/AutomationService.cs
src/IdeaStatiCa.Plugin/IAutomation.cs

#28559 - Member - Load Effects in Connection when opening via Member

---

src/IdeaStatiCa.Api/Connection/IConnectionApiController.cs
src/api-sdks/connection-api/clients/csharp/src/IdeaStatiCa.ConnectionApi/Api/TemplateApi.cs

#27945 Interface for report test

---

src/IdeaRS.OpenModel/Result/ValuesInPoint.cs
src/IdeaRS.OpenModel/Result/ValuesInSegmentSections.cs

ValuesInSegmentSections : Information about original node in mesh

---

.github/workflows/dotnet-artifacts.yml

fix artifact source dir

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Importers/CrossSectionImporter.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Importers/MemberImporter.cs
src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Utils/CssFactoryHelper.cs

28833 tekla fix rotation of member (top/bottom flange)

---

NuGet.Config
src/api-sdks/connection-api/clients/csharp/examples/ConApiWpfClient/ConApiWpfClientApp/ViewModels/MainWindowViewModel.cs
src/api-sdks/connection-api/clients/csharp/examples/ConversionBulkTool/MainWindow.xaml.cs

IdeaStatica.ConnectionApi.Examples solution build fix

---

src/IdeaRS.OpenModel/Detail/Geometry3D/Anchor3D.cs
src/IdeaRS.OpenModel/Detail/Geometry3D/BasePlate3D.cs
src/IdeaRS.OpenModel/Libraries/Material/MaterialHeadedStudGrade.cs
src/IdeaRS.OpenModel/OpenModel.cs
src/IdeaRS.OpenModel/OpenObject.cs

24697 con2det

---

src/IdeaStatiCa.BulkSelection/ItemsSorter.cs

29031 - fix for sequence contains no elements in case there are no elements on positive or negative side of plane

29031 - fix for sequence contains no elements

---

src/bim-links/tekla/IdeaStatiCa.TeklaStructuresPlugin/Importers/MemberImporter.cs

#29858 tekla fix Eccentricity fix after development

---

src/bim-links/rstab/IdeaRstabPlugin/BimApi/RstabMember.cs
src/bim-links/rstab/IdeaRstabPlugin/Factories/MemberFactory.cs
src/bim-links/rstab/IdeaRstabPlugin/PluginFactory.cs
src/bim-links/rstab/IdeaRstabPlugin/Providers/IModelDataProvider.cs
src/bim-links/rstab/IdeaRstabPlugin/Providers/ModelDataProvider.cs

Fixing issues with sync of eccentricities, which was created during development made in #988 
Getting of eccentricity was now moved to the correct level, as it was working correctly only for initial import, but was not refreshed properly during the sync.

#29812 RSTAB ecc sync fix

---

src/IdeaStatiCa.BimApiLink/Utils/CrossSectionFactoryHelper.cs

29756 add css CFU

---

src/api-sdks/rcs-api/clients/csharp/examples/CodeSamples/Inputs/rect-L-3-2.nav
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/App.xaml.cs
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/MainWindow.xaml
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/Services/DialogReinforcedCrossSectionTemplateProvider.cs
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/Services/IReinforcedCrossSectionTemplateProvider.cs
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/ViewModels/MainWindowViewModel.cs
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/ViewModels/ReinforcedCrossSectionViewModel.cs
src/api-sdks/rcs-api/clients/csharp/examples/RcsApiWpfClient/RcsApiWpfClientApp/ViewModels/SectionViewModel.cs
src/api-sdks/rcs-api/clients/python/examples/create-rf-section1/create-rf-section1-attacher.py
src/api-sdks/rcs-api/clients/python/projects/rect-L-4-2.nav

Rcsapi apply template example
